apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pg
  name: postgres-pv-claim
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
