version: '3'

services:
  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
      #postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
      #postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
    env_file:
      - .env
    volumes:
      - ./appdjango:/app
    ports:
      - 8000:8000
    command: ["gunicorn", "-c", "docker/gunicorn.py", "appdjango.wsgi:application"]
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - tutorial-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
volumes:
  tutorial-volume: null
