---

- name: Install python
  ansible.builtin.pip:
    name: docker-py

- name: Build image using cache source
  community.docker.docker_image:
    name: testmaxdev/jenkins-image:v01
    build:
      path: /var/lib/jenkins/workspace/docker-hub/app
    source: build    

- name: Log into DockerHub
  community.docker.docker_login:
    username: testmaxdev
    password: zpfybvf.cmA!

- name: Tag and push to docker hub
  community.docker.docker_image:
    name: testmaxdev/jenkins-image
    repository: testmaxdev/jenkins-image
    tag: v01
    push: true
    source: local